# Generated by Django 2.1.7 on 2021-02-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(default='Article description.', max_length=150),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
