# Generated by Django 2.1.7 on 2021-02-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210206_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='Article Detailed Explanation'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(default='Article Description', max_length=150),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Enter Article Title', max_length=80),
        ),
    ]
