# Generated by Django 2.1.7 on 2021-02-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210206_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Enter Article Title', max_length=80)),
                ('description', models.CharField(default='Article Description', max_length=150)),
            ],
        ),
    ]
