# Generated by Django 2.1.7 on 2021-02-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default='Category Description', max_length=150),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='Enter Category Name', max_length=80),
        ),
    ]
